spring.application.name=CoursesSpringMvc

spring.datasource.url=jdbc:mysql://localhost:3306/jdb
spring.datasource.username=root
spring.datasource.password=9601704554p

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always